# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: todo_group_name
  joint_model_group_pose: todo_state_name
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm_joint1_l
    - arm_joint2_l
    - arm_joint3_l
    - arm_joint4_l
    - arm_joint5_l
    - arm_joint6_l
    - arm_gripper_l
    - arm_joint1_r
    - arm_joint2_r
    - arm_joint3_r
    - arm_joint4_r
    - arm_joint5_r
    - arm_joint6_r
    - arm_gripper_r
    - front_left_hip_x
    - front_left_hip_y
    - front_left_knee
    - front_right_hip_x
    - front_right_hip_y
    - front_right_knee
    - rear_left_hip_x
    - rear_left_hip_y
    - rear_left_knee
    - rear_right_hip_x
    - rear_right_hip_y
    - rear_right_knee
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []